apiVersion: v1
kind: ServiceAccount
metadata:
  name: pytorch-xla-pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker-creator
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "create", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/status", "pods/log"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-workers
subjects:
- kind: ServiceAccount
  name: pytorch-xla-pods
roleRef:
  kind: Role
  name: worker-creator
  apiGroup: rbac.authorization.k8s.io
