apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-watcher
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-watcher
subjects:
- kind: ServiceAccount
  name: job-watcher
  namespace: default
- kind: ServiceAccount
  name: job-watcher
  namespace: automated
roleRef:
  kind: ClusterRole
  name: job-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-watcher
spec:
  selector:
    matchLabels:
      app: job-watcher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: job-watcher
    spec:
      serviceAccountName: job-watcher
      containers:
      - image: gcr.io/wcromar-tpus/job-watcher:latest
        name: job-watcher
