"apiVersion": "batch/v1"
"kind": "CronJob"
"metadata":
  "name": "cronjob-cleanup"
"spec":
  "jobTemplate":
    "spec":
      "backoffLimit": 0
      "template":
        "spec":
          "containers":
          - "args":
            - |
              cat > tests.txt <<EOF
              
              EOF
              
              delete_list=$(kubectl get cronjob --namespace=automated -l benchmarkId -o name | grep -vx -f tests.txt)
              if [[ "$delete_list" ]]; then
                kubectl delete $delete_list;
              fi
            "command":
            - "bash"
            - "-cx"
            "image": "google/cloud-sdk"
            "name": "clean"
          "restartPolicy": "Never"
          "serviceAccount": "cronjob-cleaner"
  "schedule": "0 */4 * * *"