apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-publisher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-publisher
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-publisher
subjects:
- kind: ServiceAccount
  name: event-publisher
  namespace: default
- kind: ServiceAccount
  name: event-publisher
  namespace: automated
roleRef:
  kind: ClusterRole
  name: event-publisher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-publisher-pvc
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-publisher
spec:
  selector:
    matchLabels:
      app: event-publisher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: event-publisher
    spec:
      serviceAccountName: event-publisher
      containers:
      - image: ${PUBLISHER_IMAGE_URL}
        imagePullPolicy: Always
        name: event-publisher
        args:
        - --save_dir=/workspace/
        - --pubsub_topic=${PUBSUB_TOPIC}
        - --model_output_bucket=${GCS_BUCKET}
        volumeMounts:
        - name: event-publisher-storage
          mountPath: /workspace/
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - find /tmp/health -mmin -10 | grep -qz .
          initialDelaySeconds: 60
          periodSeconds: 600
          failureThreshold: 3
      volumes:
      - name: event-publisher-storage
        persistentVolumeClaim:
          claimName: event-publisher-pvc
