# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pytorchTPU"
  pytorchTPU:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Grab latest code from master or pending PR.
      # NOTE: This affects only the code that runs here on the Github Action
      # machine. It will not affect the code that runs on the Docker image in
      # GKE. To do that, modify the Dockerfile tot checkout the desired code/branch.
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          repository: GoogleCloudPlatform/ml-testing-accelerators
          ref: ${{ github.event.pull_request.head.sha }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
